require 'mkmf'

drivers = []
in_block = false
File.readlines('go.mod').each do |line|
  if in_block
    if line =~ /([^\s]+)/
      break if $1 == ')'
      drivers << $1
    end
  else
    if line =~ /^require\s+([^\s]+)/
      if $1 == '('
        in_block = true
      else
        drivers << $1
      end
    end
  end
end

if drivers.empty?
  puts <<EOS
No drivers are registered in 'go.mod'.
You need to install at least one Go SQL driver in advance.

For example:
  go get github.com/mattn/go-sqlite3

See: https://github.com/golang/go/wiki/SQLDrivers
EOS
  exit 1
end

puts "The gosql module uses the following driver#{drivers.size == 1 ? "" : "s"}."
drivers.each do |driver|
  puts " * " + driver
end

File.write('gosql-drivers.go', <<EOS)
// DO NOT EDIT THIS FILE.
// This file is created by extconf.rb from `go.mod`.
package main
import (
\t#{drivers.map do |name| "_ \"#{name}\"" end.join("\n\t")}
)
EOS

File.write('ruby.pc', <<EOS)
Name: ruby
Description: ruby interpreper
Version: #{RUBY_VERSION}
Libs: #{RbConfig::CONFIG['LIBRUBYARG']}
Cflags: #{RbConfig::CONFIG['CFLAGS']} -I#{RbConfig::CONFIG['rubyhdrdir']} -I#{RbConfig::CONFIG['rubyarchhdrdir']}
EOS

$objs = ['gosql.o', 'libgosql.a']

$cleanfiles += ['libgosql.a', 'libgosql.h']
$distcleanfiles += ['ruby.pc', 'gosql-drivers.go']

create_makefile('gosql')
